# Generated by Django 2.2.8 on 2019-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191211_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.BooleanField(verbose_name='status'),
        ),
    ]
